name: strop_app
description: Plataforma operativa de construccion
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.10.0
  flutter: ^3.38.1

dependencies:
  audioplayers: ^6.5.1
  bloc: ^9.2.0
  cached_network_image: ^3.4.1
  camera: ^0.11.3+1
  connectivity_plus: ^7.0.0
  dio: ^5.9.1
  equatable: ^2.0.8
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  flutter_bloc: ^9.1.1
  flutter_dotenv: ^6.0.0
  flutter_image_compress: ^2.4.0
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^10.0.0
  flutter_slidable: ^4.0.3
  gap: ^3.0.1
  geolocator: ^13.0.2
  get_it: ^9.2.0
  go_router: ^17.1.0
  image_painter: ^0.7.1
  image_picker: ^1.2.1
  intl: ^0.20.2
  logger: ^2.6.2
  path: ^1.9.1
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  pretty_dio_logger: ^1.4.0
  record: ^6.2.0
  shadcn_flutter: ^0.0.51
  shared_preferences: 2.5.2
  sqflite: ^2.4.2
  supabase_flutter: ^2.12.0
  url_launcher: ^6.3.2
  uuid: ^4.5.2

dev_dependencies:
  bloc_lint: ">=0.3.3 <0.3.6"
  bloc_test: ^10.0.0
  bloc_tools: ^0.1.0-dev.20
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^10.1.0

flutter:
  generate: true
  uses-material-design: true
